name: Build and Deploy NixOS Channel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: your-cache-name
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Update packages
      run: |
        cd nixos-channel
        if [ -f update.sh ]; then
          chmod +x update.sh
          ./update.sh
        fi

    - name: Build packages
      run: |
        cd nixos-channel
        if [ -f package.nix ]; then
          nix-build package.nix
        fi

    - name: Generate store paths
      run: |
        cd nixos-channel
        # Generate store paths list
        find /nix/store -maxdepth 1 -type d -name "*" | sort > store-paths/store-paths.txt

        # Generate binary cache info
        echo "StoreDir: /nix/store" > binary-cache/nix-cache-info
        echo "WantMassQuery: 1" >> binary-cache/nix-cache-info
        echo "Priority: 30" >> binary-cache/nix-cache-info

    - name: Create channel manifest
      run: |
        cd nixos-channel
        # Create main channel file
        cat > nixos-channel << EOF2
        # NixOS Channel
        # Generated: $(date)
        # Store paths: $(wc -l < store-paths/store-paths.txt)

        This is a NixOS channel repository.

        Available endpoints:
        - /store-paths/ - Store path listings
        - /binary-cache/ - Binary cache files
        - /metadata/ - Package metadata
        EOF2

    - name: Deploy to Cloudflare Pages
      run: |
        echo "Files ready for Cloudflare Pages deployment"
        ls -la
